# Generated by Django 4.2.7 on 2023-11-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='leading_actor',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='movielist',
            old_name='leading_actress',
            new_name='actress',
        ),
    ]
