# Generated by Django 4.2.7 on 2023-11-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0007_alter_movielist_actor_alter_movielist_actress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='released',
            field=models.IntegerField(),
        ),
    ]
