# Generated by Django 4.2.7 on 2023-12-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0017_remove_movie_fun_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='female_director',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
