# Generated by Django 5.0 on 2023-12-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0020_alter_movie_best_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
