# Generated by Django 4.2.7 on 2023-11-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('leading_actor', models.CharField(max_length=30)),
                ('leading_actress', models.CharField(max_length=30)),
                ('date_watched', models.DateField()),
                ('released', models.DateField()),
            ],
        ),
    ]
