# Generated by Django 4.2.7 on 2023-11-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0006_alter_movielist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='actor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='actress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='director',
            field=models.CharField(max_length=50),
        ),
    ]
