# Generated by Django 4.2.7 on 2023-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0008_alter_movielist_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
