# Generated by Django 4.2.7 on 2023-11-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0009_alter_movielist_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieList',
            new_name='Movies',
        ),
    ]
