# Generated by Django 4.2.7 on 2023-11-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0012_alter_movie_actor_alter_movie_actress'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
