# Generated by Django 5.0.4 on 2024-05-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0023_alter_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_images',
        ),
    ]
