# Generated by Django 5.0.4 on 2024-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0024_remove_movie_movie_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='times_watched',
            field=models.IntegerField(default=0),
        ),
    ]
