# Generated by Django 5.0.4 on 2024-05-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0025_movie_times_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='times_watched',
        ),
    ]
